import ctypes
import os
import pytest
from typing import List, Tuple

# Constants mapped directly from the ST7789 specification document
ST7789_SWRESET = 0x01
ST7789_SLPOUT  = 0x11
ST7789_COLMOD  = 0x3A
ST7789_MADCTL  = 0x36
ST7789_INVON   = 0x21
ST7789_NORON   = 0x13
ST7789_DISPON  = 0x29

class SPIHardwareValidator:
    """
    Manages the Foreign Function Interface (FFI) bindings for the C telemetry engine.
    """
    def __init__(self, lib_path: str):
        # Enforce absolute path resolution to satisfy POSIX dlopen constraints
        self.abs_path = os.path.abspath(lib_path)
        
        if not os.path.exists(self.abs_path):
            raise FileNotFoundError(f"Critical Error: Shared object not found at {self.abs_path}")
        
        self.lib = ctypes.CDLL(self.abs_path)
        
        # Configure C-function signatures to ensure explicit ABI memory safety
        self.lib.ST7789_InitSequence.argtypes = [ctypes.c_void_p]
        self.lib.ST7789_InitSequence.restype = None
        
        self.lib.Mock_ResetTrace.argtypes = []
        self.lib.Mock_ResetTrace.restype = None
        
        self.lib.Mock_GetTraceSize.argtypes = []
        self.lib.Mock_GetTraceSize.restype = ctypes.c_uint32
        
        self.lib.Mock_IsCommand.argtypes = [ctypes.c_uint32]
        self.lib.Mock_IsCommand.restype = ctypes.c_uint8
        
        self.lib.Mock_GetValue.argtypes = [ctypes.c_uint32]
        self.lib.Mock_GetValue.restype = ctypes.c_uint8
        
        # Extract the memory address of the mock_spi_ops struct pointer
        self.mock_spi_ops_ptr = ctypes.addressof(ctypes.c_void_p.in_dll(self.lib, "mock_spi_ops"))

    def execute_init_sequence(self) -> None:
        self.lib.Mock_ResetTrace()
        self.lib.ST7789_InitSequence(self.mock_spi_ops_ptr)

    def retrieve_trace(self) -> List[Tuple[bool, int]]:
        size = self.lib.Mock_GetTraceSize()
        trace = []
        for i in range(size):
            is_cmd = bool(self.lib.Mock_IsCommand(i))
            val = self.lib.Mock_GetValue(i)
            trace.append((is_cmd, val))
        return trace

@pytest.fixture(scope="module")
def hardware_validator() -> SPIHardwareValidator:
    """
    Locates the compiled .so object generated by the CMake configuration.
    Assumes execution from the root project directory or the build directory.
    """
    possible_paths = [
        "libengine_mock_shared.so",
        "../build/libengine_mock_shared.so",
        "./build/libengine_mock_shared.so"
    ]
    
    for path in possible_paths:
        if os.path.exists(path):
            return SPIHardwareValidator(path)
            
    pytest.fail("Compilation prerequisite missing. Execute 'make' before running SIL tests.")

def test_st7789_initialization_sequence(hardware_validator: SPIHardwareValidator):
    """
    Validates the execution integrity of the display controller initialization sequence.
    Ensures absolute compliance with the strict command order mandated by the ST7789 datasheet.
    """
    hardware_validator.execute_init_sequence()
    trace = hardware_validator.retrieve_trace()
    
    assert len(trace) > 0, "No SPI operations were registered during initialization."
    
    # 1. Assert Software Reset
    assert trace[0] == (True, ST7789_SWRESET), "Boot sequence failure: Must initiate with SWRESET (0x01)"
    
    # 2. Assert Sleep Out transition
    assert trace[1] == (True, ST7789_SLPOUT), "Power state failure: Must transmit SLPOUT (0x11)"
    
    # 3. Assert Color Mode Configuration (Command 0x3A followed by Data 0x55 for 16-bit RGB)
    colmod_idx = trace.index((True, ST7789_COLMOD))
    assert trace[colmod_idx + 1] == (False, 0x55), "Color mode violation: RGB565 requires data 0x55"
    
    # 4. Assert Normal Display and Display On
    assert (True, ST7789_NORON) in trace, "Display operation failure: Missing NORON (0x13)"
    assert trace[-1] == (True, ST7789_DISPON), "Termination sequence failure: Final command must be DISPON (0x29)"

